version: "3.9"

services:
  ddditserver:
    build: .
    container_name: ddditserver
    ports:
      - "8080:8080"
    environment:
      GREMLIN_ENDPOINT: ${GREMLIN_ENDPOINT}
      GREMLIN_HOST: ${GREMLIN_HOST}
      GREMLIN_PORT: ${GREMLIN_PORT}
      GREMLIN_ENABLE_SSL: ${GREMLIN_ENABLE_SSL}
      GREMLIN_TRAVERSAL_SOURCE: ${GREMLIN_TRAVERSAL_SOURCE}
      GREMLIN_USERNAME: ${GREMLIN_USERNAME}
      GREMLIN_KEY: ${GREMLIN_KEY}

      COSMOS_SQL_ENDPOINT: ${COSMOS_SQL_ENDPOINT}
      COSMOS_SQL_KEY: ${COSMOS_SQL_KEY}
      COSMOS_SQL_DATABASE: ${COSMOS_SQL_DATABASE}
      COSMOS_SQL_CONTAINER_VERSIONS: ${COSMOS_SQL_CONTAINER_VERSIONS}
      COSMOS_SQL_CONTAINER_TOKEN_BLACKLIST: ${COSMOS_SQL_CONTAINER_TOKEN_BLACKLIST}

      BLOB_STORAGE_CONNECTION_STRING: ${BLOB_STORAGE_CONNECTION_STRING}
      BLOB_STORAGE_CONTAINER_MESHES: ${BLOB_STORAGE_CONTAINER_MESHES}
      BLOB_STORAGE_CONTAINER_MATERIALS: ${BLOB_STORAGE_CONTAINER_MATERIALS}

      JWT_SECRET: ${JWT_SECRET}
      MODELS_FOLDER_PATH: ${MODELS_FOLDER_PATH}

      AZURITE_BLOB_ENDPOINT: ${AZURITE_BLOB_ENDPOINT}
      AZURITE_BLOB_ACCOUNT_NAME: ${AZURITE_BLOB_ACCOUNT_NAME}
      AZURITE_BLOB_ACCOUNT_KEY: ${AZURITE_BLOB_ACCOUNT_KEY}
      AZURITE_COSMOS_ENDPOINT: ${AZURITE_COSMOS_ENDPOINT}
      AZURITE_COSMOS_ACCOUNT_KEY: ${AZURITE_COSMOS_ACCOUNT_KEY}

      FROM_EMAIL: ${FROM_EMAIL}
      TO_EMAIL: ${TO_EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}

    volumes:
      - ./data/models:/data/models
    restart: unless-stopped
